### PR TITLE
Several Improvements

### PR DESCRIPTION
**Pull request by mitchcapper**
Several improvements and additions.  I had an old clone so missed one of the official commits and re implemented those things anyway so largely just discarded the master changes from the last commit (but all features should be there).  Also fixes the items in the PR so closes #1.

### CODE REVIEW

**Comment by mitchcapper** [comment]
Also, I have a whitespace commit for my self in there but as I afterwards did the master merge you can either accept the whitespace changes, back both commits out and then just merge master and discard all changes from the merge, or try to back just that whitespace commit out but that probably will fail.

Make sure to review though with WS off to have it be meaningful: https://github.com/mrexodia/JitMagic/pull/2/files?diff=split&w=1

**Comment by mrexodia** [comment]
Thanks, I need some proper time to review this because you changed pretty much everything 😅

**Comment by mitchcapper** [comment]
Sorry, here let me change the rest :)   I also found that Redirect Guard will screw you if your config file is a symlink.  I added a fix for that.  Added the option to delay exiting for X seconds. There is no downside to delaying longer (minus longer until the process is resumed) but for debuggers that do not support events properly this would allow them to work without missing anything.

Removed old PInvoke code and switch it all to cswin32.

**Comment by mrexodia** [comment]
Just fyi, didn’t forget about this.

**Comment by mitchcapper** [comment]
I'm debating adding a blacklist option for executables.   I am guessing VS uses some special heuristic for deciding when to actually offer attaching as I certainly notice more JIT prompts than normal.    So that way if you never want to debug adobe's misbehaving program X you can blacklist it.   I don't plan to write a UI for managing already blacklisted apps though so users would have to edit the json to deblacklist something.

**Comment by mitchcapper** [comment]
Blacklisting added

**Comment by mrexodia** [comment]
Awesome, thank you! I also invited you as a collaborator if you're interested. Feel free to update the README and add yourself to the authors etc.

**Comment by mitchcapper** [comment]
@mrexodia can you enable issues for the repo ill try to handle what I can there.

**Comment by mrexodia** [comment]
Done!

**Pull request merged**
